Fix and improve e2e tests (#14)
* Fix e2e tests

* Fix e2e tests

* Fix e2e tests

* Fix e2e tests

* Fix e2e tests

* Fix e2e tests

* Fix e2e tests

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -22,13 +22,21 @@ jobs:
         run: |
           examples="$(find examples/tests/ -name main.tf | xargs -n1 dirname | xargs -n1 basename| jq -cRn '[inputs]')"
           echo "examples=${examples}" >> "$GITHUB_OUTPUT"
-  e2e:
+
+  list-clickhouse-version:
+    outputs:
+      versions: ${{ steps.list.outputs.versions }}
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      max-parallel: 10
-      matrix:
-        example: ${{ fromJSON(needs.list-examples.outputs.examples) }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - id: list
+        run: |
+          versions='["25.3", "24.8"]'
+          echo "versions=${versions}" >> "$GITHUB_OUTPUT"
+
+  build:
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -39,9 +47,42 @@ jobs:
           go-version-file: 'go.mod'
           cache: true
 
+      - name: Create tmp dir
+        run: |
+          TMPDIR="$(mktemp -d)"
+          echo "TMPDIR=$TMPDIR" >> $GITHUB_ENV
+
       - name: Build terraform provider
         run: |
-          CGO_ENABLED=0 go build -o terraform-provider-clickhousedbops
+          CGO_ENABLED=0 go build -o $TMPDIR/terraform-provider-clickhousedbops
+          
+      - uses: actions/upload-artifact@v4
+        with:
+          name: terraform-provider-clickhousedbops
+          path: ${{ env.TMPDIR }}
+
+  e2e:
+    runs-on: ubuntu-latest
+    needs: ['build', 'list-examples', 'list-clickhouse-version']
+    strategy:
+      fail-fast: false
+      max-parallel: 10
+      matrix:
+        clickhouse_version: ${{ fromJSON(needs.list-clickhouse-version.outputs.versions) }}
+        example: ${{ fromJSON(needs.list-examples.outputs.examples) }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: terraform-provider-clickhousedbops
+          path: .
+
+      - name: Adjust permissions
+        run: |
+          chmod +x ./terraform-provider-clickhousedbops
+          ls -lah
 
       - name: Install terraform
         uses: hashicorp/setup-terraform@v3
@@ -52,15 +93,29 @@ jobs:
       - name: Prepare test env
         run: |
           cd tests/
+          export CLICKHOUSE_VERSION="${{ matrix.clickhouse_version }}"
           docker compose up -d
+          sleep 5
+          
+          # Check containers are running or display logs
+          for svc in clickhouse shell ; do
+            if [ -z $(docker compose ps -q $svc) ] || [ -z $(docker ps -q --no-trunc | grep $(docker compose ps -q $svc)) ]; then
+              echo "Failed running $svc"
+              docker compose logs $svc
+              exit 1
+            fi
+          done
+          
+          docker compose exec clickhouse clickhouse client "select version()"
 
       - name: Run e2e test
         run: |
           cd tests/
           export example=${{ matrix.example }}
-          docker-compose exec shell ash -c "cd $example && terraform apply -auto-approve && terraform destroy -auto-approve"
+          docker compose exec shell ash -c "cd $example && terraform apply -auto-approve && terraform destroy -auto-approve"
 
       - name: Stop test env
+        if: always()
         run: |
           cd tests/
           docker compose kill
